### ISSUE TITLE
Cannot set font-style

### ISSUE THREAD

**Issue by camilbancioiu** [jptaranto/typey#13]
Maybe I'm doing it wrong, but my typefaces are ignoring font-style. I tried like this:

    $typefaces: (
        menu: (
            font-family: $helvetica,
            weight: bold,
            case: uppercase,
            font-style: italic,
        ),
    );

Just in case, I tried with `style: italic;` too. Either way, the definition isn't appearing in CSS. Is a typeface supposed to accept font-styles?

I'm using Typey 1.0.3.

**Comment by jptaranto** [comment]
Hey @camilbancioiu there's a feature request for it :)

I will hopefully get to it soon!

**Comment by camilbancioiu** [comment]
Ah, okay, that's cool. Thanks.

**Comment by jptaranto** [comment]
Check out the 1.1.x branch. You can use it via npm to try out this out.

I've added support for font-style called "style" to $typefaces and $typestyles.

**Comment by camilbancioiu** [comment]
Awesome, thanks!
