### ISSUE TITLE
Why the GPLv2 license instead of the MIT?

### ISSUE THREAD

**Issue by pryley** [jptaranto/typey#16]
I would like to make use of Typey in a CSS framework using NPM. While the framework does not modify Typey, I cannot include a minified version *.css because of license restrictions (the CSS framework is MIT licensed while Typey is GPLv2).

Is there a particular reason you chose the GPLv2 license for Typey?

**Comment by jptaranto** [comment]
Sorry, been awhile. I can change it to MIT if you would prefer? Honestly doesn't bother me, and MIT looks like the better choice as you've mentioned.

**Comment by pryley** [comment]
Hi @jptaranto 
MIT would be preferable as then I can also change my framework back to MIT.

**Comment by jptaranto** [comment]
Hey @pryley I have just released 1.1.2 which uses the MIT license now.
