### ISSUE TITLE
Release 1.0.0 or (at the very least) 1.0.0-beta.9

### ISSUE THREAD

**Issue by JohnAlbin** [jptaranto/typey#8]
There hasn't been any changes to the code base in a while and I _know_ this code is being used in production, so I'd recommend tagging a 1.0.0 release. Congrats!

But, please merge https://github.com/jptaranto/typey/pull/7 first. :-)

**Comment by JohnAlbin** [comment]
@jptaranto Thanks for merging #7!

Can you publish a new release so we can get those fixes in the wild?

**Comment by jptaranto** [comment]
Hey @JohnAlbin! Sorry I've only just published now. Still getting used to a certain new family member :)

It will be beta.9 for now. Waiting on full documentation and a few shorthand/helper functions for 1.0 proper.

**Comment by jptaranto** [comment]
1.0.0 tagged and released today!
